default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: me_website_development
test:
  <<: *default
  database: me_website_test
production:
  <<: *default
  database: me_website_production
  username:
  password:
